version: "3.8"
services:

  catalog_api:
    build:
      context: .
      dockerfile: src/Catalog.Service.Api/Dockerfile
    ports:
      - "5080:80"

  load_tests:
    build: test/Catalog.Service.Api.LoadTests/
    environment:
      - LOAD_TESTS_BASE_URL=http://catalog_api:80
      - LOAD_TESTS_MAX_DURATION_SEC=${LOAD_TESTS_MAX_DURATION_SEC}
    depends_on:
      - catalog_api
    volumes:
      - ./results:/opt/app/results
